[build]
  command = "npm run build"
  functions = "api"
  publish = "public"

[dev]
  autoLaunch = false
  functions = "api"
  publish = "public" # Folder with the static content for _redirect file

## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/

