[build]
  command = "npm run build"
  functions = "api"
  publish = "public"

## Uncomment to use this redirect for Single Page Applications
## like create-react-app.
## Not needed for static site generators.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  autoLaunch = false
  functions = "api"
  publish = "public" # Folder with the static content for _redirect file

## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/

